image: node:16.20.2

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g @angular/cli

build:
  stage: build
  script:
    - npm install
    - ng build --configuration production
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - apt-get update -y && apt-get install -y openssh-client rsync
    - rsync -avz -e "ssh -o StrictHostKeyChecking=no" dist/ tu-usuario@tu-ec2:/var/www/angular-app
