name: Deploy Angular to EC2

on:
  push:
    branches: [master]  # Cambia si usas otra rama

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build --prod

    - name: Deploy to EC2
      env:
        HOST: 34.228.218.191
        USER: ubuntu
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        TARGET: /var/www/angular-app
      run: |
        echo "$PRIVATE_KEY" > key.pem
        chmod 600 key.pem

        # Limpiar contenido previo del directorio en EC2
        ssh -i key.pem -o StrictHostKeyChecking=no $USER@$HOST "rm -rf $TARGET/*"

        # Subir archivos nuevos
        rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" dist/* $USER@$HOST:$TARGET
